/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ring.gltf --types 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useConfigurator } from '../contexts/Configurator';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Plane: THREE.Mesh;
		Oval_stone_gold: THREE.Mesh;
		Oval_prongs_gold: THREE.Mesh;
		Oval_setting_gold: THREE.Mesh;
		Oval_band_gold: THREE.Mesh;
		Oval_base_gold: THREE.Mesh;
		Oval_stone_blue_gold: THREE.Mesh;
		Oval_stone_pink_gold: THREE.Mesh;
		Oval_stone_yellow_gold: THREE.Mesh;
		Oval_stone_black_gold: THREE.Mesh;
		Oval_halo_band_gold: THREE.Mesh;
		Oval_halo_stones_gold: THREE.Mesh;
		Oval_stone_rose_gold: THREE.Mesh;
		Oval_band_rose_gold: THREE.Mesh;
		Oval_base_rose_gold: THREE.Mesh;
		Oval_prongs_rose_gold: THREE.Mesh;
		Oval_setting_rose_gold: THREE.Mesh;
		Oval_stone_blue_rose_gold: THREE.Mesh;
		Oval_stone_pink_rose_gold: THREE.Mesh;
		Oval_stone_yellow_rose_gold: THREE.Mesh;
		Oval_stone_black_rose_gold: THREE.Mesh;
		Oval_halo_band_rose_gold: THREE.Mesh;
		Oval_halo_stones_rose_gold: THREE.Mesh;
		Oval_stone_white_gold: THREE.Mesh;
		Oval_base_white_gold: THREE.Mesh;
		Oval_prongs_white_gold: THREE.Mesh;
		Oval_setting_white_gold: THREE.Mesh;
		Oval_band_white_gold: THREE.Mesh;
		Oval_stone_yellow_white_gold: THREE.Mesh;
		Oval_stone_blue_white_gold: THREE.Mesh;
		Oval_stone_pink_white_gold: THREE.Mesh;
		Oval_stone_black_white_gold: THREE.Mesh;
		Oval_halo_band_white_gold: THREE.Mesh;
		Oval_halo_stones_white_gold: THREE.Mesh;
		Round_base_gold: THREE.Mesh;
		Round_setting_gold: THREE.Mesh;
		Round_band_gold: THREE.Mesh;
		Round_stone_gold: THREE.Mesh;
		Round_stone_yellow_gold: THREE.Mesh;
		Round_stone_blue_gold: THREE.Mesh;
		Round_stone_pink_gold: THREE.Mesh;
		Round_stone_black_gold: THREE.Mesh;
		Round_halo_band_gold: THREE.Mesh;
		Round_halo_stones_gold: THREE.Mesh;
		Round_base_rose_gold: THREE.Mesh;
		Round_setting_rose_gold: THREE.Mesh;
		Round_band_rose_gold: THREE.Mesh;
		Round_stone_yellow_rose_gold: THREE.Mesh;
		Round_stone_rose_gold: THREE.Mesh;
		Round_stone_pink_rose_gold: THREE.Mesh;
		Round_stone_blue_rose_gold: THREE.Mesh;
		Round_stone_black_rose_gold: THREE.Mesh;
		Round_halo_band_rose_gold: THREE.Mesh;
		Round_halo_stones_rose_gold: THREE.Mesh;
		Round_base_white_gold: THREE.Mesh;
		Round_setting_white_gold: THREE.Mesh;
		Round_band_white_gold: THREE.Mesh;
		Round_stone_white_gold: THREE.Mesh;
		Round_stone_yellow_white_gold: THREE.Mesh;
		Round_stone_blue_white_gold: THREE.Mesh;
		Round_stone_pink_white_gold: THREE.Mesh;
		Round_stone_black_white_gold: THREE.Mesh;
		Round_halo_band_white_gold: THREE.Mesh;
		Round_halo_stones_white_gold: THREE.Mesh;
		Emerald_stone_white_gold: THREE.Mesh;
		Emerald_setting_white_gold: THREE.Mesh;
		Emerald_prongs_white_gold: THREE.Mesh;
		Emerald_base_white_gold: THREE.Mesh;
		Emerald_band_white_gold: THREE.Mesh;
		Emerald_stone_yellow_white_gold: THREE.Mesh;
		Emerald_stone_blue_white_gold: THREE.Mesh;
		Emerald_stone_pink_white_gold: THREE.Mesh;
		Emerald_stone_black_white_gold: THREE.Mesh;
		Emerald_halo_band_white_gold: THREE.Mesh;
		Emerald_halo_stones_white_gold: THREE.Mesh;
		Emerald_stone_gold: THREE.Mesh;
		Emerald_setting_gold: THREE.Mesh;
		Emerald_prongs_gold: THREE.Mesh;
		Emerald_base_gold: THREE.Mesh;
		Emerald_band_gold: THREE.Mesh;
		Emerald_stone_yellow_gold: THREE.Mesh;
		Emerald_stone_pink_gold: THREE.Mesh;
		Emerald_stone_blue_gold: THREE.Mesh;
		Emerald_stone_black_gold: THREE.Mesh;
		Emerald_halo_band_gold: THREE.Mesh;
		Emerald_halo_stones_gold: THREE.Mesh;
		Emerald_stone_rose_gold: THREE.Mesh;
		Emerald_setting_rose_gold: THREE.Mesh;
		Emerald_prongs_rose_gold: THREE.Mesh;
		Emerald_base_rose_gold: THREE.Mesh;
		Emerald_band_rose_gold: THREE.Mesh;
		Emerald_stone_yellow_rose_gold: THREE.Mesh;
		Emerald_stone_pink_rose_gold: THREE.Mesh;
		Emerald_stone_blue_rose_gold: THREE.Mesh;
		Emerald_stone_black_rose_gold: THREE.Mesh;
		Emerald_halo_band_rose_gold: THREE.Mesh;
		Emerald_halo_stones_rose_gold: THREE.Mesh;
		Asscher_base_gold: THREE.Mesh;
		Asscher_setting_gold: THREE.Mesh;
		Asscher_band_gold: THREE.Mesh;
		Asscher_stone_gold: THREE.Mesh;
		Asscher_stone_yellow_gold: THREE.Mesh;
		Asscher_stone_blue_gold: THREE.Mesh;
		Asscher_stone_pink_gold: THREE.Mesh;
		Asscher_stone_black_gold: THREE.Mesh;
		Asscher_halo_band_gold: THREE.Mesh;
		Asscher_halo_stones_gold: THREE.Mesh;
		Asscher_base_white_gold: THREE.Mesh;
		Asscher_setting_white_gold: THREE.Mesh;
		Asscher_band_white_gold: THREE.Mesh;
		Asscher_stone_white_gold: THREE.Mesh;
		Asscher_stone_yellow_white_gold: THREE.Mesh;
		Asscher_stone_blue_white_gold: THREE.Mesh;
		Asscher_stone_pink_white_gold: THREE.Mesh;
		Asscher_stone_black_white_gold: THREE.Mesh;
		Asscher_halo_band_white_gold: THREE.Mesh;
		Asscher_halo_stones_white_gold: THREE.Mesh;
		Asscher_base_rose_gold: THREE.Mesh;
		Asscher_setting_rose_gold: THREE.Mesh;
		Asscher_band_rose_gold: THREE.Mesh;
		Asscher_stone_rose_gold: THREE.Mesh;
		Asscher_stone_yellow_rose_gold: THREE.Mesh;
		Asscher_stone_blue_rose_gold: THREE.Mesh;
		Asscher_stone_pink_rose_gold: THREE.Mesh;
		Asscher_stone_black_rose_gold: THREE.Mesh;
		Asscher_halo_band_rose_gold: THREE.Mesh;
		Asscher_halo_stones_rose_gold: THREE.Mesh;
	};
	materials: {
		floor: THREE.MeshStandardMaterial;
		diamond_pure: THREE.MeshPhysicalMaterial;
		gold: THREE.MeshStandardMaterial;
		diamond_blue: THREE.MeshStandardMaterial;
		diamond_pink: THREE.MeshStandardMaterial;
		diamond_yellow: THREE.MeshStandardMaterial;
		diamond_black: THREE.MeshStandardMaterial;
		rose_gold: THREE.MeshStandardMaterial;
		white_gold: THREE.MeshStandardMaterial;
	};
	// animations: GLTFAction[]
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function Ring(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('./models/ring.gltf') as GLTFResult;
	const { shape, bandColor, hasHalo, stoneColor } = useConfigurator();

	return (
		<group {...props} dispose={null}>
			<PerspectiveCamera
				makeDefault={false}
				far={1000}
				near={0.1}
				fov={21.458}
				position={[0.18, 14.762, -17.85]}
				rotation={[-2.578, -0.006, -3.138]}
				scale={6.246}
			/>
			<mesh
				geometry={nodes.Plane.geometry}
				material={materials.floor}
				scale={3.269}
				visible={false}
			/>
			{shape === 'Oval' && (
				<>
					{bandColor === 'gold' && (
						<>
							<mesh
								geometry={nodes.Oval_stone_gold.geometry}
								material={materials.diamond_pure}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_prongs_gold.geometry}
								material={materials.gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_setting_gold.geometry}
								material={materials.gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_band_gold.geometry}
								material={materials.gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_base_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Oval_stone_blue_gold.geometry}
									material={materials.diamond_blue}
									position={[0.012, 2.777, -0.001]}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Oval_stone_pink_gold.geometry}
									material={materials.diamond_pink}
									position={[0.012, 2.777, -0.001]}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Oval_stone_yellow_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.012, 2.777, -0.001]}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Oval_stone_black_gold.geometry}
									material={materials.diamond_black}
									position={[0.012, 2.777, -0.001]}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Oval_halo_band_gold.geometry}
										material={materials.gold}
										position={[0.014, 2.596, -0.005]}
										scale={0.34}
										visible={true}
									/>
									<mesh
										geometry={nodes.Oval_halo_stones_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.111, 3, -0.331]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.079, 0.048, 0.048]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'rose_gold' && (
						<>
							<mesh
								geometry={nodes.Oval_stone_rose_gold.geometry}
								material={materials.diamond_pure}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_band_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_base_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_prongs_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_setting_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_blue_rose_gold.geometry}
								material={materials.diamond_blue}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_pink_rose_gold.geometry}
								material={materials.diamond_pink}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_yellow_rose_gold.geometry}
								material={materials.diamond_yellow}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_black_rose_gold.geometry}
								material={materials.diamond_black}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_halo_band_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.014, 2.596, -0.005]}
								scale={0.34}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_halo_stones_rose_gold.geometry}
								material={materials.diamond_pure}
								position={[-1.111, 3, -0.331]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={[0.079, 0.048, 0.048]}
								visible={true}
							/>
						</>
					)}
					{bandColor === 'white_gold' && (
						<>
							<mesh
								geometry={nodes.Oval_stone_white_gold.geometry}
								material={materials.diamond_pure}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_base_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_prongs_white_gold.geometry}
								material={materials.white_gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_setting_white_gold.geometry}
								material={materials.white_gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_band_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_yellow_white_gold.geometry}
								material={materials.diamond_yellow}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_blue_white_gold.geometry}
								material={materials.diamond_blue}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_pink_white_gold.geometry}
								material={materials.diamond_pink}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_stone_black_white_gold.geometry}
								material={materials.diamond_black}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_halo_band_white_gold.geometry}
								material={materials.white_gold}
								position={[0.014, 2.596, -0.005]}
								scale={0.34}
								visible={true}
							/>
							<mesh
								geometry={nodes.Oval_halo_stones_white_gold.geometry}
								material={materials.diamond_pure}
								position={[-1.111, 3, -0.331]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={[0.079, 0.048, 0.048]}
								visible={true}
							/>
						</>
					)}
				</>
			)}
			{shape === 'Round' && (
				<>
					{bandColor === 'gold' && (
						<>
							<mesh
								geometry={nodes.Round_base_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_setting_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_band_gold.geometry}
								material={materials.gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Round_stone_gold.geometry}
									material={materials.diamond_pure}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Round_stone_yellow_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Round_stone_blue_gold.geometry}
									material={materials.diamond_blue}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Round_stone_pink_gold.geometry}
									material={materials.diamond_pink}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Round_stone_black_gold.geometry}
									material={materials.diamond_black}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Round_halo_band_gold.geometry}
										material={materials.gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Round_halo_stones_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'rose_gold' && (
						<>
							<mesh
								geometry={nodes.Round_base_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_setting_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_band_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Round_stone_yellow_rose_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Round_stone_rose_gold.geometry}
									material={materials.diamond_pure}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Round_stone_pink_rose_gold.geometry}
									material={materials.diamond_pink}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Round_stone_blue_rose_gold.geometry}
									material={materials.diamond_blue}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Round_stone_black_rose_gold.geometry}
									material={materials.diamond_black}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Round_halo_band_rose_gold.geometry}
										material={materials.rose_gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Round_halo_stones_rose_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'white_gold' && (
						<>
							<mesh
								geometry={nodes.Round_base_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_setting_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Round_band_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Round_stone_white_gold.geometry}
									material={materials.diamond_pure}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Round_stone_yellow_white_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Round_stone_blue_white_gold.geometry}
									material={materials.diamond_blue}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Round_stone_pink_white_gold.geometry}
									material={materials.diamond_pink}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Round_stone_black_white_gold.geometry}
									material={materials.diamond_black}
									position={[0.004, 2.897, -0.012]}
									rotation={[0, Math.PI / 2, 0]}
									scale={0.442}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Round_halo_band_white_gold.geometry}
										material={materials.white_gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Round_halo_stones_white_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
				</>
			)}
			{shape === 'Emerald' && (
				<>
					{bandColor === 'white_gold' && (
						<>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Emerald_stone_white_gold.geometry}
									material={materials.diamond_pure}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							<mesh
								geometry={nodes.Emerald_setting_white_gold.geometry}
								material={materials.white_gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_prongs_white_gold.geometry}
								material={materials.white_gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_base_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_band_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Emerald_stone_yellow_white_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Emerald_stone_blue_white_gold.geometry}
									material={materials.diamond_blue}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Emerald_stone_pink_white_gold.geometry}
									material={materials.diamond_pink}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Emerald_stone_black_white_gold.geometry}
									material={materials.diamond_black}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Emerald_halo_band_white_gold.geometry}
										material={materials.white_gold}
										position={[0.014, 2.596, -0.005]}
										scale={0.34}
										visible={true}
									/>
									<mesh
										geometry={nodes.Emerald_halo_stones_white_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.111, 3, -0.331]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.079, 0.048, 0.048]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'gold' && (
						<>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Emerald_stone_gold.geometry}
									material={materials.diamond_pure}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							<mesh
								geometry={nodes.Emerald_setting_gold.geometry}
								material={materials.gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_prongs_gold.geometry}
								material={materials.gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_base_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_band_gold.geometry}
								material={materials.gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Emerald_stone_yellow_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Emerald_stone_pink_gold.geometry}
									material={materials.diamond_pink}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Emerald_stone_blue_gold.geometry}
									material={materials.diamond_blue}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Emerald_stone_black_gold.geometry}
									material={materials.diamond_black}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Emerald_halo_band_gold.geometry}
										material={materials.gold}
										position={[0.014, 2.596, -0.005]}
										scale={0.34}
										visible={true}
									/>
									<mesh
										geometry={nodes.Emerald_halo_stones_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.111, 3, -0.331]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.079, 0.048, 0.048]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'rose_gold' && (
						<>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Emerald_stone_rose_gold.geometry}
									material={materials.diamond_pure}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							<mesh
								geometry={nodes.Emerald_setting_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.259, 2.749, -0.404]}
								scale={-0.053}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_prongs_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.012, 2.777, -0.001]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_base_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.224, 0.062, 0.224]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Emerald_band_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Emerald_stone_yellow_rose_gold.geometry}
									material={materials.diamond_yellow}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Emerald_stone_pink_rose_gold.geometry}
									material={materials.diamond_pink}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Emerald_stone_blue_rose_gold.geometry}
									material={materials.diamond_blue}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Emerald_stone_black_rose_gold.geometry}
									material={materials.diamond_black}
									position={[0.008, 2.794, 0.002]}
									scale={0.805}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Emerald_halo_band_rose_gold.geometry}
										material={materials.rose_gold}
										position={[0.014, 2.596, -0.005]}
										scale={0.34}
										visible={true}
									/>
									<mesh
										geometry={nodes.Emerald_halo_stones_rose_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.111, 3, -0.331]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.079, 0.048, 0.048]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
				</>
			)}
			{shape === 'Asscher' && (
				<>
					{bandColor === 'gold' && (
						<>
							<mesh
								geometry={nodes.Asscher_base_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_setting_gold.geometry}
								material={materials.gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_band_gold.geometry}
								material={materials.gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Asscher_stone_gold.geometry}
									material={materials.diamond_pure}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Asscher_stone_yellow_gold.geometry}
									material={materials.diamond_yellow}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Asscher_stone_blue_gold.geometry}
									material={materials.diamond_blue}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Asscher_stone_pink_gold.geometry}
									material={materials.diamond_pink}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Asscher_stone_black_gold.geometry}
									material={materials.diamond_black}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Asscher_halo_band_gold.geometry}
										material={materials.gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Asscher_halo_stones_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'white_gold' && (
						<>
							<mesh
								geometry={nodes.Asscher_base_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_setting_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_band_white_gold.geometry}
								material={materials.white_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Asscher_stone_white_gold.geometry}
									material={materials.diamond_pure}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Asscher_stone_yellow_white_gold.geometry}
									material={materials.diamond_yellow}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Asscher_stone_blue_white_gold.geometry}
									material={materials.diamond_blue}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Asscher_stone_pink_white_gold.geometry}
									material={materials.diamond_pink}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Asscher_stone_black_white_gold.geometry}
									material={materials.diamond_black}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Asscher_halo_band_white_gold.geometry}
										material={materials.white_gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Asscher_halo_stones_white_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
					{bandColor === 'rose_gold' && (
						<>
							<mesh
								geometry={nodes.Asscher_base_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.432, -0.012]}
								scale={[0.279, 0.078, 0.279]}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_setting_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 2.897, -0.012]}
								scale={0.442}
								visible={true}
							/>
							<mesh
								geometry={nodes.Asscher_band_rose_gold.geometry}
								material={materials.rose_gold}
								position={[0.004, 1.265, -0.012]}
								rotation={[Math.PI / 2, 0, 0]}
								scale={0.442}
								visible={true}
							/>
							{stoneColor === 'diamond_pure' && (
								<mesh
									geometry={nodes.Asscher_stone_rose_gold.geometry}
									material={materials.diamond_pure}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_yellow' && (
								<mesh
									geometry={nodes.Asscher_stone_yellow_rose_gold.geometry}
									material={materials.diamond_yellow}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_blue' && (
								<mesh
									geometry={nodes.Asscher_stone_blue_rose_gold.geometry}
									material={materials.diamond_blue}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_pink' && (
								<mesh
									geometry={nodes.Asscher_stone_pink_rose_gold.geometry}
									material={materials.diamond_pink}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{stoneColor === 'diamond_black' && (
								<mesh
									geometry={nodes.Asscher_stone_black_rose_gold.geometry}
									material={materials.diamond_black}
									position={[0, 2.9, 0]}
									rotation={[0, -0.831, 0]}
									scale={0.734}
									visible={true}
								/>
							)}
							{hasHalo && (
								<>
									<mesh
										geometry={nodes.Asscher_halo_band_rose_gold.geometry}
										material={materials.rose_gold}
										position={[0.005, 2.603, -0.009]}
										scale={0.328}
										visible={true}
									/>
									<mesh
										geometry={nodes.Asscher_halo_stones_rose_gold.geometry}
										material={materials.diamond_pure}
										position={[-1.082, 2.993, -0.324]}
										rotation={[Math.PI / 2, 0, 0]}
										scale={[0.076, 0.046, 0.046]}
										visible={true}
									/>
								</>
							)}
						</>
					)}
				</>
			)}
		</group>
	);
}

useGLTF.preload('./models/ring.gltf');
